version: '3.3'
services:
  app:
    build: .
    command: python manage.py runserver 0:8000
    volumes:
      - ./core/:/app/core/
      - ./api/:/app/api/
      - ./apps/:/app/apps/
      - ./static/:/app/static/
    ports:
      - 8000:8000
    env_file:
      - ./core/.env
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: env("SQL_USER")
      POSTGRES_PASSWORD: env("SQL_PASSWORD")
      POSTGRES_DB: env("SQL_DATABASE")
    ports:
      - "5433:5432"
